### ISSUE TITLE
Illegal string offset for Headlines

### ISSUE THREAD

**Issue by jaroslavlibal** [taufik-nurrohman/parsedown-extra-plugin#20]
Hello,

I am facing an issue when trying the code below:

    $this->parsedown->text('# Header {.sth}');

It ends up with a warning `Illegal string offset 'argument'` on line 297 of the ParsedownExtraPlugin.php

    296:            } else if ($Mode === 'argument') {
    297:                $Element['handler']['argument'] = $Content;
    298:            } else {

**Comment by taufik-nurrohman** [comment]
This extension was intended to be used with Parsedown Extra 0.8. What Parsedown Extra version are you using?

**Comment by jaroslavlibal** [comment]
I am using Parsedown Extra 0.8.1 as I have installed your plugin via composer.

**Comment by taufik-nurrohman** [comment]
See the reference issue in the last commit [here](https://github.com/taufik-nurrohman/parsedown-extra-plugin/commit/9f9b507f67bedd4daadbb12fe577d88a6b527489).

FYI, the composer version is not created by me. So the code is already outdated. I will remove the `composer.json` file next time. Unless I can get the package name back from the author.

You will need to contact [him](https://github.com/taufik-nurrohman/parsedown-extra-plugin/issues/16#issuecomment-646757385) to delete the composer package so that I can re-create the package later and maintaining it using my composer account.

**Comment by jaroslavlibal** [comment]
Thanks, I did not notice that the canonical repository URLin the packagist does not correspond to your original github repo :-(

You probably don't need to remove your composer.json as it looks correct, I'd rather try the following:
- Fix the required erusev/parsedown-extra version in composer.json on 0.8.0 instead of ~0.8, which will also install 0.8.1.
- Ask the @pixeline as the pacakagist package maintainer to change the canonical URL to your original repository instead of his fork and make you a maintainer or rename/delete his package.

**Comment by pixeline** [comment]
I just did as requested. Let me know if that works !
