### ISSUE TITLE
Attributes for <p>

### ISSUE THREAD

**Issue by KoljaL** [taufik-nurrohman/parsedown-extra-plugin#23]
Is there a way to set attributes to a paragraph?

Maybe in this way:

markdown:
```
{span.foo}
This is a text
{span}
```

html:
```
<span class="foo">
This is a text
</span>
```

**Comment by taufik-nurrohman** [comment]
Some extensions such as [this](https://kramdown.gettalong.org/syntax.html#attribute-list-definitions) can do, but that violates the original Markdown philosophy: that is to stay readable even from reading the plain version of the Markdown document.

> Readability, however, is emphasized above all else. A Markdown-formatted document should be publishable _as-is_, as plain text, without looking like it’s been marked up with tags or formatting instructions.
>
> Markdown is _not_ a replacement for HTML, or even close to it. Its syntax is very small, corresponding only to a very small subset of HTML tags. The idea is _not to create a syntax that makes it easier to insert HTML tags_. In my opinion, HTML tags are already easy to insert. The idea for Markdown is to make it easy to read, write, and edit prose.
> https://daringfireball.net/projects/markdown/syntax#philosophy

I am one of those who against such features, which has made the Markdown syntax even more complex that non-technical people have to learn the markup just to be able to read it. Hence, in that situation, writing Markdown is no different than writing HTML, for the average person. As if we are learning a new syntax in order to convert it into the syntax we are familiar with —HTML.

In my opinion, there are two solutions that can be taken without breaking the Markdown philosophy:

 1. Use HTML syntax as-is, and just write `<p class="foo">…</p>` (because Markdown is not a replacement for HTML).
 2. Use the embedded syntax feature (blocks, shortcodes, etc.) from the respective Content Management System where available (for example, by writing syntax such as `[p class="foo" text="…"/]`). Since it is a different syntax, so it will not be considered Markdown.

**Comment by KoljaL** [comment]
Thank you for making your point of view clear to me. Generally speaking, as the author of the parsedown extension, I think you're absolutely right. It doesn't solve my problem, but it does show that I should do it in a different way. (regex for example)

P.S.
If I may, one more personal question:
How would you solve the problem if you had to format paragraphs differently with Markdown (different text colors for example)?

**Comment by taufik-nurrohman** [comment]
> How would you solve the problem if you had to format paragraphs differently with Markdown?

People don&rsquo;t usually create different paragraph styles in random places. I am assuming that you are trying to make custom paragraph style as an article prologue like this:

![Prologue](https://user-images.githubusercontent.com/1669261/109971585-ff47ee00-7d28-11eb-9c32-993068e60a10.png)

Let&rsquo;s say, I am now using a content management system that allows me to insert meta description data using the available custom field feature. Then I will use that data to separate the main paragraph from the content:
``` .yaml
---
title: Laman atau Halaman?
description: Selama ini mungkin kita telah salah dalam menggunakan istilah ‘laman’ di internet.
...

Markdown content goes here.
```

Then, on the current theme you use, you can output the description data into a hard-coded paragraph tag with a special class name:

``` .php
<h2><?= $page['title']; ?></h2>
<?php if (!empty($page['description'])): ?>
<p class="special"><?= $page['description']; ?></p>
<?php endif; ?>
<?= echo (new ParsedownExtraPlugin)->text($page['content']); ?>
```

I would choose custom field solution and the like.

**Comment by KoljaL** [comment]
My application isn't that complex and I don't use a CMS either.  
But the idea with the CSS selector is very good, because the approaches always alternate:

```css
p:nth-child(even) {
  background-color: red;
}
p:nth-child(odd) {
  background-color: blue;
}
```

Thanks for pointing out my solution
